version: '3.9'
services:
  app:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "node src/server.js"
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=benchmark
      - POSTGRES_PASSWORD=benchmark
      - POSTGRES_DB=benchmark_lab
      - MONGO_URI=mongodb://mongo:27017/benchmark_lab
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - mongo
      - openldap
      - graphql-target

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=benchmark
      - POSTGRES_PASSWORD=benchmark
      - POSTGRES_DB=benchmark_lab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./infra/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro



  graphql-target:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "node infra/graphql/server.js"
    ports:
      - "4000:4000"
    volumes:
      - ./:/app

  openldap:
    image: osixia/openldap:1.5.0
    environment:
      - LDAP_ORGANISATION=Benchmark Lab
      - LDAP_DOMAIN=benchmark.local
      - LDAP_ADMIN_PASSWORD=benchmark
    ports:
      - "389:389"
      - "636:636"

volumes:
  postgres_data:
  mongo_data:
